        CCCCCCCCCCCCC               AAA         TTTTTTTTTTTTTTTTTTTTTTT   SSSSSSSSSSSSSSS 
     CCC::::::::::::C              A:::A        T:::::::::::::::::::::T SS:::::::::::::::S
   CC:::::::::::::::C             A:::::A       T:::::::::::::::::::::TS:::::SSSSSS::::::S
  C:::::CCCCCCCC::::C            A:::::::A      T:::::TT:::::::TT:::::TS:::::S     SSSSSSS
 C:::::C       CCCCCC           A:::::::::A     TTTTTT  T:::::T  TTTTTTS:::::S            
C:::::C                        A:::::A:::::A            T:::::T        S:::::S            
C:::::C                       A:::::A A:::::A           T:::::T         S::::SSSS         
C:::::C                      A:::::A   A:::::A          T:::::T          SS::::::SSSSS    
C:::::C                     A:::::A     A:::::A         T:::::T            SSS::::::::SS  
C:::::C                    A:::::AAAAAAAAA:::::A        T:::::T               SSSSSS::::S 
C:::::C                   A:::::::::::::::::::::A       T:::::T                    S:::::S
 C:::::C       CCCCCC    A:::::AAAAAAAAAAAAA:::::A      T:::::T                    S:::::S
  C:::::CCCCCCCC::::C   A:::::A             A:::::A   TT:::::::TT      SSSSSSS     S:::::S
   CC:::::::::::::::C  A:::::A               A:::::A  T:::::::::T      S::::::SSSSSS:::::S
     CCC::::::::::::C A:::::A                 A:::::A T:::::::::T      S:::::::::::::::SS 
        CCCCCCCCCCCCCAAAAAAA                   AAAAAAATTTTTTTTTTT       SSSSSSSSSSSSSSS
